version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: citasalut-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: citasalut
    ports:
      - "3306:3306"
    volumes:
      # Conecta tu carpeta local 'database' con el inicio de MySQL
      - ./database:/docker-entrypoint-initdb.d